apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  MPT_DJANGO_SECRET_KEY: {{ .Values.global.DjangoSecretKey }}
  MPT_API_TOKEN_OPERATIONS: {{ .Values.global.MptOperationApiToken }}
  MPT_TOOL_STORAGE_AIRTABLE_API_KEY: {{ .Values.global.MptToolStorageAirtableApiKey }}
  EXT_WEBHOOKS_SECRETS: {{ .Values.global.WebhookSecretKeys }}
  EXT_AIRTABLE_API_TOKEN: {{ .Values.global.AirTableApiToken }}
  EXT_NAV_AUTH_CLIENT_ID: {{ .Values.global.NavAuthClientId }}
  EXT_NAV_AUTH_CLIENT_SECRET: {{ .Values.global.NavAuthClientSecret }}
  EXT_MSTEAMS_WEBHOOK_URL: {{ .Values.global.MsTeamsWebhookUrl }}
  EXT_AWS_SES_CREDENTIALS: {{ .Values.global.AwsSesCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}.files
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  adobe_credentials.json:  {{ .Values.global.CredentialsJson }}
  adobe_authorizations.json: {{ .Values.global.AuthorizationsJson }}
